"""
src/report/writer.py
====================
Saves one-shot Q&A answers as Markdown reports under ``reports/``.
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from pathlib import Path


_REPORT_DIR = Path("reports")


def write_report(
    repo_url: str,
    question: str,
    selected_files: list[dict],
    answer: str,
    branch: str | None = None,
) -> Path:
    """
    Persist a Q&A report to ``reports/report_<timestamp>.md``.

    Parameters
    ----------
    repo_url:       The analysed GitHub repository URL.
    question:       The user's question.
    selected_files: List of file-metadata dicts chosen by the agent.
    answer:         The LLM-generated answer.
    branch:         Git branch that was analysed (``None`` → "default").

    Returns
    -------
    The :class:`~pathlib.Path` of the written report file.
    """
    _REPORT_DIR.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(tz=timezone.utc)
    filename = f"report_{timestamp.strftime('%Y%m%dT%H%M%SZ')}.md"
    report_path = _REPORT_DIR / filename

    # Build selected-files list
    file_lines = "\n".join(
        f"- `{f.get('path', '<unknown>')}`"
        for f in (selected_files or [])
    ) or "_No files selected._"

    branch_display = branch or "default"

    content = f"""\
# GitHub Code-Analyser Report

| Field | Value |
|---|---|
| **Repository** | {repo_url} |
| **Branch** | `{branch_display}` |
| **Generated** | {timestamp.strftime('%Y-%m-%d %H:%M:%S UTC')} |

---

## Question

> {question}

---

## Files Analysed

{file_lines}

---

## Answer

{answer}

---

_Generated by [GitHub Code-Analyser Agent](https://github.com)_
"""

    report_path.write_text(content, encoding="utf-8")
    return report_path
